Lesson 4
SARGEFORCE/SargeStore pull request #5
Opened 2019-11-23 08:27 UTC by SARGEFORCE

Доделал, но не заполняется модель, ошибка нв странице NullReferenceException: Object reference not set to an instance of an object. Захожу в отладку а там Model в секциях - Null :(

2019-11-23 12:13 UTC, Infarh requested changes
Нужно подкорректировать и всё заработает.

2019-11-23 12:13 UTC, Infarh commented on SargeStore/Views/Home/Partial/_LeftSideBar.cshtml
> +﻿<div class="left-sidebar">
Данное представление надо перенести из директории представлений контролера `Home `в директорию общих представлений `Shared/Partial`

2019-11-23 12:13 UTC, Infarh commented on SargeStore/ViewComponents/SectionsViewComponent.cs
> +        public IViewComponentResult Invoke() => View();
Вызов представления без передачи ему модели карается исключительной ситуацией.

```
public IViewComponentResult Invoke() => View(GetSections());
```

2019-11-24 14:02 UTC, SARGEFORCE commented on SargeStore/ViewComponents/SectionsViewComponent.cs
> +        public IViewComponentResult Invoke() => View();
Пропустил, спасибо :) Исправил - завелось!

2019-11-24 14:02 UTC, merged